version: 2

sources:
   - name: raw
     schema: gz_raw_data
     tables: 
       - name: sales
         identifier: raw_gz_sales
         description: Sales of Greenweez / We renamed a column for more clarity
         tests:
          - unique:
              column_name: "orders_id || '-' || pdt_id"
       - name: product
         identifier: raw_gz_product
         description: List of GreenWeez's products / Change type and name of a column
         columns:
           - name: products_id
             tests:
                - unique        
       - name: ship
         identifier: raw_gz_ship
         description: List of shipping fee of GreenWeez'product / change type of a column, avoiding conflict
         columns:
           - name: orders_id
             tests:
               - unique
       - name: adword
         identifier: raw_gz_adwords
         tests:
          - unique:
              column_name: "date_date || '-' || paid_source || '-' || campaign_key"
       - name: bing
         identifier: raw_gz_bing
         tests:
           - unique:
               column_name: "date_date || '-' || paid_source || '-' || campaign_key"
       - name: facebook
         identifier: raw_gz_facebook
         tests:
           - unique:
               column_name: "date_date || '-' || paid_source || '-' || campaign_key"
       - name: criteo
         identifier: raw_gz_criteo
         tests:
           - unique:
               column_name: "date_date || '-' || paid_source || '-' || campaign_key"
